스켈레톤 코드 생성
ara-official/TriQuiz pull request #17
Opened 2021-02-21 16:18 UTC by MinSikSon

nestjs 에서 제공하는 기본 명령어로 스켈레톤 코드 생성하였음.

2021-02-21 16:19 UTC, MinSikSon commented on BackEnd/README.md
> +- Insomnia Core 다운로드
readme.md 이외, 아래 파일은 ```$ sudo nest new triquiz-be``` 수행 결과로 생성된 것들 입니다.

2021-02-21 16:26 UTC, throw-Exceptions requested changes

2021-02-21 16:26 UTC, throw-Exceptions commented on BackEnd/triquiz-be/src/main.ts
> +  await app.listen(3000);
FE에서 포트 번호를 3000을 쓰고 있는데 리액트는 포트 변경을 위한 코드가 깔끔하지 않아서 BE포트를 다른걸로 변경했으면 좋겠음..! 로컬에서 테스트 하려면 포트가 같으면 안되니까~~

2021-02-22 08:34 UTC, MinSikSon commented on BackEnd/triquiz-be/src/main.ts
> +  await app.listen(3000);
백엔드 포트번호 8000으로 할까염?

2021-02-22 09:25 UTC, throw-Exceptions commented on BackEnd/triquiz-be/src/main.ts
> +  await app.listen(3000);
3000 초과면 아무거나 괜찮을듯!! 원하는걸루해~

2021-02-22 13:25 UTC, jaehunchoi approved these changes
port 8000번 변경 확인

2021-02-22 13:25 UTC, jaehunchoi commented on BackEnd/triquiz-be/src/main.ts
> +  await app.listen(8000);
8000번 확인

2021-02-22 13:25 UTC, merged